export const OctoCatdata = {
    "login": "octocat",
    "id": 1,
    "node_id": "MDQ6VXNlcjE=",
    "avatar_url": "https://github.com/images/error/octocat_happy.gif",
    "gravatar_id": "",
    "url": "https://api.github.com/users/octocat",
    "html_url": "https://github.com/octocat",
    "followers_url": "https://api.github.com/users/octocat/followers",
    "following_url": "https://api.github.com/users/octocat/following{/other_user}",
    "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
    "organizations_url": "https://api.github.com/users/octocat/orgs",
    "repos_url": "https://api.github.com/users/octocat/repos",
    "events_url": "https://api.github.com/users/octocat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/octocat/received_events",
    "type": "User",
    "site_admin": false,
    "name": "monalisa octocat",
    "company": "GitHub",
    "blog": "https://github.com/blog",
    "location": "San Francisco",
    "email": "octocat@github.com",
    "hireable": false,
    "bio": "There once was...",
    "twitter_username": "monatheoctocat",
    "public_repos": 2,
    "public_gists": 1,
    "followers": 20,
    "following": 0,
    "created_at": "2008-01-14T04:33:35Z",
    "updated_at": "2008-01-14T04:33:35Z"
  }

  export const jduellData =  
  {
    "login": "jduell12",
    "id": 32172119,
    "node_id": "MDQ6VXNlcjMyMTcyMTE5",
    "avatar_url": "https://avatars3.githubusercontent.com/u/32172119?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jduell12",
    "html_url": "https://github.com/jduell12",
    "followers_url": "https://api.github.com/users/jduell12/followers",
    "following_url": "https://api.github.com/users/jduell12/following{/other_user}",
    "gists_url": "https://api.github.com/users/jduell12/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jduell12/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jduell12/subscriptions",
    "organizations_url": "https://api.github.com/users/jduell12/orgs",
    "repos_url": "https://api.github.com/users/jduell12/repos",
    "events_url": "https://api.github.com/users/jduell12/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jduell12/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Jessica Duell",
    "company": null,
    "blog": "",
    "location": "Apex, North Carolina",
    "email": null,
    "hireable": null,
    "bio": "A full time student working on full stack development at Lambda School!",
    "twitter_username": null,
    "public_repos": 97,
    "public_gists": 1,
    "followers": 8,
    "following": 6,
    "created_at": "2017-09-21T15:37:35Z",
    "updated_at": "2020-07-07T15:51:17Z"
  }

export const Mdata = {
  "login": "MaryamMosstoufi",
  "id": 11998558,
  "node_id": "MDQ6VXNlcjExOTk4NTU4",
  "avatar_url": "https://avatars2.githubusercontent.com/u/11998558?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/MaryamMosstoufi",
  "html_url": "https://github.com/MaryamMosstoufi",
  "followers_url": "https://api.github.com/users/MaryamMosstoufi/followers",
  "following_url": "https://api.github.com/users/MaryamMosstoufi/following{/other_user}",
  "gists_url": "https://api.github.com/users/MaryamMosstoufi/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/MaryamMosstoufi/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/MaryamMosstoufi/subscriptions",
  "organizations_url": "https://api.github.com/users/MaryamMosstoufi/orgs",
  "repos_url": "https://api.github.com/users/MaryamMosstoufi/repos",
  "events_url": "https://api.github.com/users/MaryamMosstoufi/events{/privacy}",
  "received_events_url": "https://api.github.com/users/MaryamMosstoufi/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Maryam Mosstoufi",
  "company": "ZOOXOOS INC.",
  "blog": "",
  "location": "North Bethesda, MD",
  "email": null,
  "hireable": null,
  "bio": "Everything Technology, Design and Business.",
  "twitter_username": null,
  "public_repos": 35,
  "public_gists": 0,
  "followers": 15,
  "following": 25,
  "created_at": "2015-04-17T18:38:10Z",
  "updated_at": "2020-07-07T13:30:02Z"
} 
export const sageData ={
  "login": "sage-jordan",
  "id": 50002551,
  "node_id": "MDQ6VXNlcjUwMDAyNTUx",
  "avatar_url": "https://avatars1.githubusercontent.com/u/50002551?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/sage-jordan",
  "html_url": "https://github.com/sage-jordan",
  "followers_url": "https://api.github.com/users/sage-jordan/followers",
  "following_url": "https://api.github.com/users/sage-jordan/following{/other_user}",
  "gists_url": "https://api.github.com/users/sage-jordan/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/sage-jordan/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/sage-jordan/subscriptions",
  "organizations_url": "https://api.github.com/users/sage-jordan/orgs",
  "repos_url": "https://api.github.com/users/sage-jordan/repos",
  "events_url": "https://api.github.com/users/sage-jordan/events{/privacy}",
  "received_events_url": "https://api.github.com/users/sage-jordan/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Sage Jordan",
  "company": null,
  "blog": "",
  "location": "Indianapolis, IN",
  "email": null,
  "hireable": null,
  "bio": "Lambda School Student <3",
  "twitter_username": null,
  "public_repos": 96,
  "public_gists": 0,
  "followers": 25,
  "following": 12,
  "created_at": "2019-04-26T01:09:48Z",
  "updated_at": "2020-06-19T23:01:31Z"
}
export const tsData={
  "login": "tsbarrett89",
  "id": 47550906,
  "node_id": "MDQ6VXNlcjQ3NTUwOTA2",
  "avatar_url": "https://avatars0.githubusercontent.com/u/47550906?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/tsbarrett89",
  "html_url": "https://github.com/tsbarrett89",
  "followers_url": "https://api.github.com/users/tsbarrett89/followers",
  "following_url": "https://api.github.com/users/tsbarrett89/following{/other_user}",
  "gists_url": "https://api.github.com/users/tsbarrett89/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/tsbarrett89/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/tsbarrett89/subscriptions",
  "organizations_url": "https://api.github.com/users/tsbarrett89/orgs",
  "repos_url": "https://api.github.com/users/tsbarrett89/repos",
  "events_url": "https://api.github.com/users/tsbarrett89/events{/privacy}",
  "received_events_url": "https://api.github.com/users/tsbarrett89/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Thomas Barrett",
  "company": null,
  "blog": "thomasbarrett.dev",
  "location": "Missoula, MT",
  "email": null,
  "hireable": null,
  "bio": "Full Stack Web Development Student at Lambda School.",
  "twitter_username": null,
  "public_repos": 111,
  "public_gists": 0,
  "followers": 15,
  "following": 18,
  "created_at": "2019-02-12T05:33:04Z",
  "updated_at": "2020-07-06T16:20:43Z"
}
export const eData = {
  "login": "emilioramirezeguia",
  "id": 13247374,
  "node_id": "MDQ6VXNlcjEzMjQ3Mzc0",
  "avatar_url": "https://avatars3.githubusercontent.com/u/13247374?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/emilioramirezeguia",
  "html_url": "https://github.com/emilioramirezeguia",
  "followers_url": "https://api.github.com/users/emilioramirezeguia/followers",
  "following_url": "https://api.github.com/users/emilioramirezeguia/following{/other_user}",
  "gists_url": "https://api.github.com/users/emilioramirezeguia/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/emilioramirezeguia/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/emilioramirezeguia/subscriptions",
  "organizations_url": "https://api.github.com/users/emilioramirezeguia/orgs",
  "repos_url": "https://api.github.com/users/emilioramirezeguia/repos",
  "events_url": "https://api.github.com/users/emilioramirezeguia/events{/privacy}",
  "received_events_url": "https://api.github.com/users/emilioramirezeguia/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Emilio Ramirez",
  "company": "Pininos",
  "blog": "http://www.emilioramirez.com/",
  "location": "Rosarito, Mexico",
  "email": null,
  "hireable": true,
  "bio": null,
  "twitter_username": null,
  "public_repos": 37,
  "public_gists": 0,
  "followers": 24,
  "following": 22,
  "created_at": "2015-07-09T02:14:19Z",
  "updated_at": "2020-07-07T06:01:15Z"
}
export const rData = {
  "login": "Roboblox",
  "id": 19676961,
  "node_id": "MDQ6VXNlcjE5Njc2OTYx",
  "avatar_url": "https://avatars1.githubusercontent.com/u/19676961?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Roboblox",
  "html_url": "https://github.com/Roboblox",
  "followers_url": "https://api.github.com/users/Roboblox/followers",
  "following_url": "https://api.github.com/users/Roboblox/following{/other_user}",
  "gists_url": "https://api.github.com/users/Roboblox/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Roboblox/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Roboblox/subscriptions",
  "organizations_url": "https://api.github.com/users/Roboblox/orgs",
  "repos_url": "https://api.github.com/users/Roboblox/repos",
  "events_url": "https://api.github.com/users/Roboblox/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Roboblox/received_events",
  "type": "User",
  "site_admin": false,
  "name": "John Schuler",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 74,
  "public_gists": 1,
  "followers": 9,
  "following": 9,
  "created_at": "2016-06-01T00:06:41Z",
  "updated_at": "2020-07-07T20:03:58Z"
}